### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Gronis** [T-vK/NodeMCU-Express#1]
Hi!

Nice little library you have here! I would like to use it, but the problem is that you do not have a software license attached to it.

Would you mind adding a license to it? It will be much easier for others to correctly use this software if it is correctly licensed. If you do not care how others will use it, and only want to protect yourself against lawsuits etc, I would recommend MIT or Apache 2.0 license for this project, as they are fairly open. If you want to restrict any projects using this library to open source, there are other licenses available.

**Comment by T-vK** [comment]
Sure, I'll add an MIT license.

Edit:
Added the MIT license to both, the master and dev branch.

**Comment by Gronis** [comment]
Great! :)
